### ISSUE TITLE
EarthMC Essentials can't work on fabric api version 0.78.0 (latest version)

### ISSUE THREAD

**Issue by nokteholda** [Warriorrrr/EarthMCEssentials#14]
![image](https://user-images.githubusercontent.com/69749293/231710366-d3a07737-4df6-41ca-8cec-7d8d9935f566.png)
please fix that

**Error code:**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'EarthMCEssentials' (emc-essentials) v4.0.0-1.19.4 with any version that is compatible with:
		 - fabric-api 0.78.0+1.19.4
Unmet dependency listing:
	 - Mod 'EarthMCEssentials' (emc-essentials) v4.0.0-1.19.4 requires version 0.76.0 of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.78.0+1.19.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Owen3H** [comment]
Fixed in d1a5ee9
